apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-app
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-app
  namespace: production
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-app
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-app
subjects:
- kind: ServiceAccount
  name: k8s-app
  namespace: production
